# Generated by Django 4.2.11 on 2024-04-22 09:25

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_phone_number"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="phone number"
            ),
        ),
    ]
