# Generated by Django 4.2.11 on 2024-04-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_user_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(auto_now=True, verbose_name="date joined"),
        ),
    ]
