# Generated by Django 4.2.11 on 2024-05-07 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_user_date_joined_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                error_messages={
                    "unique": "A user with this phone number already exists."
                },
                max_length=15,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^09\\d{9}$", "Enter a valid phone number."
                    )
                ],
                verbose_name="phone number",
            ),
        ),
    ]
